export const COLORS = {
  PURPLE: "#7C3AED",
  PURPLE_LIGHT: "#EDE9FE",
  PURPLE_MID: "#A78BFA",
  GRAY: "#6B7280",
  GRAY_LIGHT: "#F3F4F6",
  WHITE: "#FFFFFF",
  TEXT: "#111827",
  TEXT_MUTED: "#6B7280",
};

export const styles = {
  app: {
    fontFamily: "'Nunito', 'Poppins', sans-serif",
    minHeight: "100vh",
    background: "#F5F3FF",
    display: "flex",
    flexDirection: "row",
  },
  sidebar: {
    width: 260,
    background: COLORS.WHITE,
    borderRight: "1px solid #E5E7EB",
    display: "flex",
    flexDirection: "column",
    padding: "24px 0",
    boxShadow: "0 1px 3px rgba(0,0,0,0.1)",
  },
  sidebarLogo: {
    fontSize: 24,
    fontWeight: 900,
    color: COLORS.PURPLE,
    paddingLeft: 24,
    marginBottom: 32,
  },
  sidebarNav: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    gap: 8,
    paddingLeft: 12,
    paddingRight: 12,
  },
  navItem: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "12px 16px",
    borderRadius: 12,
    background: "transparent",
    border: "none",
    cursor: "pointer",
    fontSize: 14,
    fontWeight: 500,
    color: COLORS.TEXT_MUTED,
    transition: "all 0.2s",
  },
  navItemActive: {
    background: COLORS.PURPLE_LIGHT,
    color: COLORS.PURPLE,
    fontWeight: 600,
  },
  phone: {
    flex: 1,
    background: COLORS.WHITE,
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
    position: "relative",
  },
  statusBar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "12px 20px 4px",
    fontSize: 12,
    fontWeight: 600,
    color: COLORS.TEXT,
  },
  screen: {
    flex: 1,
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
  },
};
